#baseurl = "http://www.khalid.se"
baseurl="https://khaal.github.io"
title = "khalid.se"
languagecode = "en"
defaultcontentlanguage = "en"
paginate = 20

#theme = "hugo-theme-nostyleplease"
#theme = "ananke"
theme = "hugo-coder"


[markup.highlight]
style = "github-dark"

[params]
  author = "Khalid R."
  info = "Welcome to my personal spot on the web."
  description = "Khalid's personal website"
  keywords = "blog,personal,NGO"
  avatarurl = "images/selfie_dither.png"

#  faviconSVG = "/img/favicon.svg"
#  favicon_32 = "/img/favicon-32x32.png"
#  favicon_16 = "/img/favicon-16x16.png"


  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/khaal/"

[[params.social]]
  name = "Mastodon"
  icon = "fa fa-mastodon fa-2x"
  weight = 2
  url = "https://swecyb.com/@khalid"
  
[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-linkedin fa-2x"
  weight = 3
  url = "https://www.linkedin.com/in/khalidra/"
  
  
[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"


# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "/posts"
[[menu.main]]
  name = "About"
  weight = 2
  url = "/about"
  
[[menu.main]]
  name = "Contact"
  url = "/contact"
  weight = 3
