#baseurl = "http://www.khalid.se"
baseurl="https://khaal.github.io"
title = "khalid.se"


#theme = "hermit-V2"
theme = "hugo-theme-nostyleplease"
#theme = "ananke"
#theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

[markup.highlight]
style = "github-dark"

[params]
  author = "Khalid"
  info = "Welcome to my personal spot on the web."
  description = "Khalid's personal website"
  keywords = "blog,personal,NGO"
  avatarurl = "images/selfie_dither.png"

#  faviconSVG = "/img/favicon.svg"
#  favicon_32 = "/img/favicon-32x32.png"
#  favicon_16 = "/img/favicon-16x16.png"


  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"


# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "/posts"
[[menu.main]]
  name = "About"
  weight = 2
  url = "/about"
  
[[menu.main]]
  name = "Contact"
  url = "/contact"
  weight = 3
